name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v2
        
      - name: Setando Node.js e Buildando
        uses: actions/setup-node@v1
        with:
          node-version: '18'
          
      - name: instalando dependencia e buildando web-app
        run: |
          npm ci
          npm run build

      - name: subindo para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
